name: telegram_flet
description: "A new Flutter project for Telegram client"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0
  http: ^0.13.6
  dio: ^5.4.0
  path: ^1.8.3
  intl: ^0.19.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/