#name: Build APK

#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
#  workflow_dispatch:

#jobs:
#  build:
#    runs-on: ubuntu-latest
    
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
      
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v2
      
#    - name: Build Docker image and APK
#      run: |
#        docker buildx create --use
#        docker buildx build --platform linux/amd64 -t telethod-builder . --load
#        docker run --rm -v ${PWD}:/app telethod-builder
        
#    - name: Upload APK
#      uses: actions/upload-artifact@v3
#      with:
#        name: app-release
#        path: build/app/outputs/apk/release/*.apk
#        retention-days: 7