name: Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          openjdk-11-jdk \
          autoconf \
          automake \
          libtool \
          pkg-config

    - name: Install Android SDK & NDK
      run: |
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        sudo mkdir -p /usr/local/android-sdk/cmdline-tools
        sudo unzip commandlinetools-linux-9477386_latest.zip -d /usr/local/android-sdk/cmdline-tools
        sudo mv /usr/local/android-sdk/cmdline-tools/cmdline-tools /usr/local/android-sdk/cmdline-tools/latest
        export ANDROID_HOME=/usr/local/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0" "ndk;23.1.7779620"

    - name: Build APK
      run: |
        export ANDROID_HOME=/usr/local/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        buildozer android debug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: telegram-manager-debug
        path: bin/*.apk
        retention-days: 90 