name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Create .env file
        run: |
          touch .env
          echo "API_ID=${{ secrets.TELEGRAM_API_ID }}" >> .env
          echo "API_HASH=${{ secrets.TELEGRAM_API_HASH }}" >> .env
          cat .env
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3'
          channel: 'stable'
          
      - name: Install Flutter dependencies
        run: flutter pub get
        
      - name: Generate Gradle Wrapper
        run: |
          cd android
          gradle wrapper
          chmod +x gradlew
          ./gradlew --version
          cd ..
        
      - name: Build APK
        run: flutter build apk --release
        
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
