name: Python Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements-frontend.txt ]; then pip install -r requirements-frontend.txt; fi
          if [ -f requirements-backend.txt ]; then pip install -r requirements-backend.txt; fi
      
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Create necessary directories
        run: |
          mkdir -p sessions
          mkdir -p chat
      
      - name: Create env file
        run: |
          echo "API_ID=${{ secrets.API_ID }}" > .env
          echo "API_HASH=${{ secrets.API_HASH }}" >> .env
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }} 